### PR TITLE
Add Fedora 26 ppc64 LE/BE

### PR DESCRIPTION
**Pull request by hodgesto**
Taste Results - 
 - [x] Fedora 26 BE - https://pastebin.osuosl.org/68031/

Inspec Results -

### CODE REVIEW

**Comment by hodgesto** [comment]
[Fedora ppc64 template fix up to pass openstack_taster](https://trello.com/c/W14dRvuI/497-fedora-ppc64-template-fix-up-to-pass-openstacktaster)

**Comment by knightsamar** [comment]
Rebased on master and pushed. Build will trigger and update results here.

**Comment by doublej472** [comment]
@ramereth I think this is good for review!

**Comment by knightsamar** [comment]
I rebased this on #47's branch. Should deploy rightly and then test correctly.

**Comment by ramereth** [comment]
Closed in favor of #52

**Pull request closed without merging**
