### PR TITLE
Update to CentOS 7.5

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
[CentOS 7.5](https://trello.com/c/2LzJbH40/800-centos-75)

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by ramereth** [comment]
!deploy

**Comment by osuosl-manatee** [comment]
Error: Cannot merge PR because it would create merge conflicts.

**Pull request merged**
