### PR TITLE
Adding initial draft of bento pipeline diagram

### PR DESCRIPTION
**Pull request by knightsamar**

### CODE REVIEW

**Comment by knightsamar** [comment]
@DesertBeagle does the diagram in the .svg file make sense from what we discussed?

**Comment by DesertBeagle** [comment]
It does, but I thought we were going from deploy to openstack_taster. Is that just the way it would work? Also, are we including jenkins slave choice in this digram?
Also, I thought it would be `!taste` and `!deploy`, since `taste!` and `deploy!` could be used in a conversation.

**Comment by knightsamar** [comment]
@DesertBeagle good catch. Fixed both.

**Comment by DesertBeagle** [comment]
@knightsamar It kind of looks like the testing flow goes into the !delpoy section. Also, this is just a general flow, not including the jenkins slave choice, right?

**Comment by knightsamar** [comment]
>@knightsamar It kind of looks like the testing flow goes into the !delpoy section.

@DesertBeagle yeah, I have been trying to make it look separate but haven't succeeded. For now, all nodes in color signify starting points. 

>Also, this is just a general flow, not including the jenkins slave choice, right?

Yes, I plan to make a zoomed version/write down details soon.

@ramereth could you please take a look at the diagram and let me know what you think and what details would you like to see ? And probably also point out what I am doing wrong that I don't get grouped nodes properly.

**Comment by knightsamar** [comment]
Stalling the addition of a zoomed diagram and more details for this, until I actually create a working jenkins job/pipeline/thing in kitchen vm and have the whole picture clear.

**Comment by ramereth** [comment]
@knightsamar want to clean the merge conflict up and then I'll do one final review on it?

**Pull request closed without merging**
