### PR TITLE
OpenStack Mitaka images

### PR DESCRIPTION
**Pull request by ramereth**
This builds two types of images:

1. All-in-One (AIO) Mitaka image (includes controller and compute services)
2. Identity (keystone) + rabbitmq + mariadb

The purpose of this is to allow two things:

1. The AIO image will be used in the Newton branch to test upgrading from Mitaka to Newton using test-kitchen.
2. Speed up test-kitchen runtimes for Mitaka by having the bare essentials for most services already pre-installed. Most services (such as glance, neutron, etc) all need keystone and its deps which takes extra time to build for each suite. Since we already test this in other suites we don't need to replicate it.

These templates are built using the same kickstart and scripts as the other CentOS 7 images however it also does the following:

- Add support for using Berks to install cookbooks locally if a Berksfile exists for a particular template in a specific standard location.
- Using chef, use the osl-cookbook to deploy the AIO and identity images
- All of the data bags and roles were taken from osl-openstack so that they transfer properly when used there.
- Disable and stop all openstack, rabbitmq and mariadb services

The last point is needed since the hostnames will differ between the image and when you deploy in test-kitchen. Rabbitmq will fail on the first run if its already running using these images, so this works around this issue. It also speeds up start time since none of those services will be started on boot.

This replaces osuosl/bento#30

### CODE REVIEW

**Comment by ramereth** [comment]
@knightsamar you should be building with ``-c -v 12.18.31``.

**Comment by knightsamar** [comment]
So, `identity` was built successfully, but `aio` had a failure in Chef steps.

Stacktrace:https://pastebin.osuosl.org/60601/

**Comment by ramereth** [comment]
@knightsamar looks like a new release of the systemd cookbook came out and broke that recipe. osuosl-cookbooks/osl-openstack#89 should fix that once its merged.

**Comment by knightsamar** [comment]
So I get this now: https://pastebin.osuosl.org/61556/

```
Unable to find a solution for demands: aliases (0.1.2), base (1.12.0), firewall (4.4.0), ibm-power (1.0.0), openstack-block-storage (13.0.0), openstack-common (13.0.0), openstack-compute (13.0.0), openstack-dashboard (13.0.0), openstack-identity (13.0.0), openstack-image (13.0.0), openstack-integration-test (13.0.0), openstack-network (13.0.0), openstack-ops-database (13.0.0), openstack-ops-messaging (13.0.0), openstack-orchestration (13.0.0), openstack-telemetry (13.0.0), openstack_test (0.1.0), osl-apache (2.8.1), osl-munin (1.0.1), osl-nrpe (2.1.0), osl-openstack (2.5.3), resource_from_hash (0.1.5), statsd (0.1.6), yum-qemu-ev (1.1.2)
```

I have trying deleting `chef/berkshelf` too.

**Comment by ramereth** [comment]
@knightsamar I believe I have finally fixed any remaining Berkshelf issues.

**Comment by knightsamar** [comment]
@ramereth looks good. qemu is working on the vm right now. 
Will come back tomorrow with the final result.

**Pull request merged**
