### PR TITLE
Ubuntu 14.04 LE/BE ppc images

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
[Ubuntu 14.04 / 17.10 ppc](https://trello.com/c/lu4hFm0F/673-ubuntu-1404-1710-ppc)

**Comment by Codysseus** [comment]
testing comment for research

**Comment by Codysseus** [comment]
Comment testing try #2

**Comment by ramereth** [comment]
I'm closing this in favor of splitting up BE and LE into two PR's

**Pull request closed without merging**
