### PR TITLE
Add Fedora 25 on ppc

### PR DESCRIPTION
**Pull request by doublej472**
This is a substantial rebase of https://github.com/osuosl/packer-templates/pull/16, which adds Fedora 25 support to PPC platforms.

### CODE REVIEW

**Comment by doublej472** [comment]
[Fedora ppc64 template fix up to pass openstack_taster](https://trello.com/c/W14dRvuI/497-fedora-ppc64-template-fix-up-to-pass-openstacktaster)

**Comment by knightsamar** [comment]
It looks like a build for this won't be triggered unless something is pushed which results in a `synchronized` event. https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by ramereth** [comment]
According to the jenkins log it seems that taster isn't working exactly right:

```
[packer_pipeline] Running shell script
+ ./bin/taster_wrapper.rb -t fedora-25-ppc64-openstack.json -s /home/alfred/openstack_credentials.json -r 43
{:template_file=>"fedora-25-ppc64-openstack.json", :openstack_credentials_file=>"/home/alfred/openstack_credentials.json", :pr_number=>"43"}
cluster is openpower-controller.osuosl.org
+--------------------------------------+-------------------------------+--------+
| ID                                   | Name                          | Status |
+--------------------------------------+-------------------------------+--------+
| 077d4e2e-89a9-472f-9fe8-8a96d47c3e2a | CentOS 7.2 BE                 | active |
| cec2e3ce-668a-486c-9904-ff278041aefa | CentOS 7.2 LE                 | active |
| 063d2ae6-9256-4dc3-9b11-56f9f015cef4 | CentOS 7.3 BE                 | active |
| c2458b3f-3dc6-4178-b50d-c0e5903b38f4 | CentOS 7.3 BE - PR#43         | active |
| b0cfefd8-ce5b-4495-bdaf-baf163676819 | CentOS 7.3 LE                 | active |
| 4b3a51a4-a321-4a16-9e3c-50c22ef69f40 | CentOS 7.3 LE - PR#43         | active |
| d5967b70-c382-4caa-bb6e-e55137bfc4ac | Debian 8 BE                   | active |
| 7b7d0d8b-b150-4e9d-90b3-45e0b202ce3e | Debian 8 LE                   | active |
| e53474a8-5f0a-4f7e-8a39-ecd9d895849d | Debian 8.9 BE - PR#36         | active |
| b27853b4-4a62-4969-9d52-f643e9b9ff0f | Debian 8.9 BE - PR#36         | active |
| 983ecabb-56c9-4a6a-978a-a77a731f0536 | Debian 8.9 BE - PR#36         | active |
| e687cca3-327f-4904-bc4b-487bcd35db76 | Debian 8.9 BE doublejtest     | active |
| 0646ee7b-25b5-409e-81c0-40972c45df04 | Debian 8.9 Big Endian - PR#36 | active |
| 516cab03-7b7b-4157-ba73-7704720d0051 | Debian 8.9 LE - PR#36         | active |
| 5c4f92bb-ff28-4218-9823-16c4107cc019 | Debian 8.9 LE - PR#36         | active |
| a54ec0bb-1986-4f04-a502-97796ff33a9c | Debian 8.9 LE - PR#36         | active |
| 9ff9aa28-057b-40e4-85ba-38b87ac6436e | Debian 8.9 LE - PR#36         | active |
| a2e0eebd-22b0-4b34-b42f-24985a02ae3e | Debian 8.9 LE doublejtest     | active |
| 231ba1af-0a33-421f-a3aa-d45f1c492bcf | Debian 9.1 LE doublejtest     | active |
| 9474c0fb-ce9b-4789-92fc-db6881ac74e4 | Debian 9.2 LE doublejtest     | active |
| 167925da-1d15-4c2a-827e-4eec5b745085 | Fedora 23 BE                  | active |
| b93dd996-726d-4f27-8f6c-a4fe5a88f646 | Fedora 23 LE                  | active |
| 7368ebec-08ec-448a-b30c-762047c73fb2 | Fedora 24 BE                  | active |
| 6a8a0c1d-cc7d-42e2-81f9-bd5ff137cbd7 | Fedora 24 LE                  | active |
| d5f69859-c62f-490a-a860-69539b921e7c | Fedora 25 BE doublejtest      | active |
| df80d413-fffc-497c-b353-3627bb84a11c | Fedora 25 LE doublejtest      | active |
| 5bc3fa08-d706-402e-97f8-6e7ee699caaf | Fedora 26 LE doublejtest      | active |
| 63573f1f-7996-4fd7-beaa-fcb9211e7b89 | OpenSUSE Leap 42.2 LE         | active |
| b5816223-1e22-4138-9627-a685d9d99173 | Ubuntu 14.04 BE               | active |
| 6559fa2b-6f61-4171-8c4a-b9b9db4d1722 | Ubuntu 14.04 LE               | active |
| 36ea43ad-e611-4712-8c52-32beff43e7d7 | Ubuntu 16.04 BE               | active |
| 913b0781-490b-4f45-8c8b-e080c943bde0 | Ubuntu 16.04 BE doublejtest   | active |
| fa267123-fe50-435b-a11b-cf325152da05 | Ubuntu 16.04 LE               | active |
| 27ab980e-8c92-4b7e-9d82-13a7f0bed718 | Ubuntu 16.04 LE doublejtest   | active |
| c7bc6960-7760-44c6-8041-906e57a09690 | Ubuntu 16.10 BE               | active |
| 7bb6a444-91ee-4935-b04e-b914936f7da8 | Ubuntu 16.10 LE               | active |
+--------------------------------------+-------------------------------+--------+
openstack_taster "Fedora 25 BE - PR#43"
WARN: Unresolved specs during Gem::Specification.reset:
      builder (>= 2.1.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fedora 25 BE - PR#43 is not an available image.

cluster is openpower-openstack.testing.osuosl.org
The request you have made requires authentication. (HTTP 401) (Request-ID: req-bb2d7a26-f9ff-47e3-ab4a-5fcb69a097cc)

openstack_taster "Fedora 25 BE - PR#43"
WARN: Unresolved specs during Gem::Specification.reset:
      builder (>= 2.1.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/middlewares/expects.rb:7:in `response_call': Expected([200, 204]) <=> Actual(401 Unauthorized) (Excon::Error::Unauthorized)
excon.error.response
  :body          => "{\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "114"
    "Content-Type"           => "application/json"
    "Date"                   => "Sat, 21 Oct 2017 00:40:40 GMT"
    "Server"                 => "Apache"
    "Vary"                   => "X-Auth-Token"
    "WWW-Authenticate"       => "Keystone uri=\"https://openpower-openstack.testing.osuosl.org:5000\""
    "x-openstack-request-id" => "req-885ead38-0dae-49ad-bf53-07a04a41a9b8"
  }
  :host          => "openpower-openstack.testing.osuosl.org"
  :local_address => "10.1.1.48"
  :local_port    => 47184
  :path          => "/v2.0/tokens"
  :port          => 5000
  :reason_phrase => "Unauthorized"
  :remote_ip     => "140.211.9.95"
  :status        => 401
  :status_line   => "HTTP/1.1 401 Unauthorized\r\n"
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/connection.rb:389:in `response'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.59.0/lib/excon/connection.rb:253:in `request'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.21/lib/fog/openstack.rb:438:in `retrieve_tokens_v2'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.21/lib/fog/openstack.rb:192:in `authenticate_v2'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.21/lib/fog/openstack.rb:150:in `authenticate'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.21/lib/fog/openstack/core.rb:182:in `authenticate'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-openstack-0.1.21/lib/fog/compute/openstack.rb:392:in `initialize'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/openstack_taster-1.0.1/bin/openstack_taster:92:in `<top (required)>'
	from /opt/chef/embedded/bin/openstack_taster:22:in `load'
	from /opt/chef/embedded/bin/openstack_taster:22:in `<main>'
```
@knightsamar

**Comment by knightsamar** [comment]
@ramereth issue being addressed in #47 (deploy_wrapper and taster_wrapper suffer from the similar problem of not collecting the status and using it reliably)

**Comment by ramereth** [comment]
closed in favor of #52

**Pull request closed without merging**
