### PR TITLE
CentOS 7.4

### PR DESCRIPTION
**Pull request by ramereth**
For now, ignore the mitaka images as I'll be fixing those up for newton soon.

### CODE REVIEW

**Comment by ramereth** [comment]
Looks like like packer pipeline is smart than me and is going force me to fix the the mitaka templates.

**Comment by ramereth** [comment]
[CentOS 7.4 BE / LE / x86](https://trello.com/c/ZM1C12mK/626-centos-74-be-le-x86)

**Comment by ramereth** [comment]
I had to fix a few more things on the x86 openstack cluster to get this build to work. I tested the regular x86 image and it passes (see below). For now I'd like to ignore the other failures as its' primarily issues with openstack_taster and would rather we get this moved ASAP.

@osuosl/chefs please review!

```
$ openstack_taster "CentOS 7.4 - PR#53"
Tasting CentOS 7.4 - PR#53 as 'taster-20180129_103558-centos-53' with username 'centos'.
Building...
Sleeping 30 seconds for OS startup...
Testing for instance '9db9b389-b061-4b5f-9078-33a0ee11b217'.
[DEPRECATION] `processes.list` is deprecated. Please use `processes.entries` instead. It will be removed in version 2.0.0.

Profile: OpenPower Security Test Suite (openpower_security)
Version: 1.0.2
Target:  ssh://centos@140.211.168.117:22

  ✔  security-1.0: Openstack Image Security Test
     ✔  saved sshd config should not permit root login
     ✔  saved sshd config should not permit password authentication
     ✔  saved sshd config should not permit challenge response authentication
     ✔  saved sshd config should not permit keyboard interactive authentication
     ✔  running sshd config should not permit root login
     ✔  running sshd config should not permit password authentication
     ✔  running sshd config should not permit challenge response authentication
     ✔  running sshd config should not permit keyboard interactive authentication
     ✔  Processes sshd list.length should eq 1
     ✔  Command sudo -U centos -l stdout should cmp == /\(ALL\) ((NO)*PASSWD)*: ALL/
  ✔  ports-1.0: Openstack Image Ports Test
     ✔  Port  with protocol =~ /tcp/ port != 22 should not be listening
     ✔  Port  with protocol =~ /udp/ port != 68 process != "dhclient" should not be listening

Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 12 successful, 0 failures, 0 skipped
Attaching volume 'test' (aab6e9ea-6b8d-4ae0-af29-d0ea2fd4083b)...
Sleeping 20 seconds for attachment persistance...
Logging partition list and dmesg...
Mounting volume 'test' (aab6e9ea-6b8d-4ae0-af29-d0ea2fd4083b)...
Mounting from inside the instance...
Detaching test.

Encountered 0 failures.
Destroying instance for session 26719140.
```

**Comment by doublej472** [comment]
The base centos images LGTM!

**Pull request merged**
