### PR TITLE
Standardize vm_name

### PR DESCRIPTION
**Pull request by doublej472**
vm_name should reflect the json file it is a part of, see this [issue](https://github.com/osuosl/packer-templates/issues/31) for more info.

### CODE REVIEW

**Comment by knightsamar** [comment]
LGTM!

@ramereth to go with the convention should we also rename the mitaka-identity and mitaka-aio templates and `vm_name` to have `openstack` suffix at the end ?

**Comment by ramereth** [comment]
@knightsamar If it helps keeping things simple then I'm fine with that.

**Comment by ramereth** [comment]
@doublej472 can you please also update those templates as well in this PR?

**Comment by knightsamar** [comment]
@ramereth Fixed. Could you please review it?

**Pull request merged**
