### PR TITLE
Add Debian ppc64 templates

### PR DESCRIPTION
**Pull request by doublej472**
~**This is a preliminary PR**, this only makes sense to view changes relative to [doublej472/fix-ubuntu](https://github.com/osuosl/packer-templates/tree/doublej472/fix-ubuntu), not master. As soon as that PR is merged this will be ready to be merged. In the mean time, this has been created so that it can be reviewed by people who are interested.~

### **This should be good to review on it's own now**

This PR adds support for Debian 8 on ppc64 and ppc64le, and Debian 9 for ppc64le. The scripts are heavily based off of the Ubuntu 16.04 PR, with some Debian specific changes.

A major change that needed to be made is that Debian 8 (BE & LE) does **not** include `ppc64-diag` in the package repos. This means that we have to build them separately and add them to our own [apt repository](https://git.osuosl.org/osuosl/apt-repo/tree/master). Doing so requires that we add our GPG key and repository information to the apt sources before we can install our packages. Debian 9 packages this, so we don't have to do the same thing there.

### CODE REVIEW

**Comment by ramereth** [comment]
[Debian ppc64 template fix up to pass openstack_taster](https://trello.com/c/FzObOO9T/496-debian-ppc64-template-fix-up-to-pass-openstacktaster)

**Comment by doublej472** [comment]
@ramereth This should be ready for review!

**Comment by knightsamar** [comment]
Rebased on master.

**Comment by knightsamar** [comment]
Re-rebased on master

**Comment by knightsamar** [comment]
Results are out! Failures are for the `volumes` test suite.

**Pull request merged**
